### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sedwards2009** [sedwards2009/extraterm#30]
This issue is for tracking issue priorities and their rough order of implementation.

Note: This can change at anytime without warning. It might even just be out of date at times

- [ ] Add reload CSS command #26 
- [ ] Option to remove the window title bar #27
- [ ] More options for the 'show' command #28
- [ ] More options for the 'from' command #29

**Comment by cprog** [comment]
Hi, 
Could you add quake mode support ?

**Comment by cprog** [comment]
@sedwards2009 Thank you.

**Comment by BonLouis** [comment]
Hi, hope it's the place.
Do you plan to integrate a programmatic way of openning multiple Extraterm with own process running in?
Good job for the almost fullfilled roadmap !

**Comment by sedwards2009** [comment]
@BonLouis  can you make a new issue here and describe in more detail what you mean? I don't quite understand what you are requesting.

**Comment by sedwards2009** [comment]
@BonLouis Also, the roadmap isn't approaching fulfillment. I just need to update it and fill in my stuff to do. :smile:

**Comment by joedf** [comment]
add Quake mode and fullscreen to that list. 😎

**Comment by sedwards2009** [comment]
@joedf  it is possible to set a global shortcut to open up Extraterm. So you can get fairly close to a quake mode.

No plans for full screen beyond just plain old maximising the window.

**Comment by talicz** [comment]
Hi @sedwards2009, I have been using Terminator for Linux for years. What I love there is that you can split the view to see more consoles in a single Tab (similar to what you do in Extraterm), but you can group all the terminals within the Tab to type and execute the same command on all of the at once. This is super handy when working multiple nodes of the same cluster.

I cannot find a single terminal emulator for Windows that would offer me this option. Please consider adding to the roadmap. Extraterm is a very nice piece of work.

Additional info:
Windows offer a Linux Subsystem where Linux apps can be run.
WSL2 ... I intended to use Terminal there, but the problem is that it does not work together with corporate VPN. (I found many complains on web about it.)
WSL1 ... This one works fine with corporate VPNs, but does not run GUI based apps (like Terminator)

This is the reason why I am looking for a new Windows-based Terminator alternative.

**Comment by Belgabor** [comment]
> I cannot find a single terminal emulator for Windows that would offer me this option. Please consider adding to the roadmap. Extraterm is a very nice piece of work.
> 
Technically (probably) not really the right place to say this, but Tabby can do that if you can deal with an Electron based terminal emulator.

**Comment by sedwards2009** [comment]
@Belgabor How does Tabby deal with it? How are the tabs selected which should receive the input? Is it just all of the tabs/panes in a window?

Splits and "input broadcast" are not the same thing. One way to do "input broadcast" would be first a way to "link" any number of terminals (regardless of which window they are in) and then have input to a linked terminal automatically be sent to the others.

**Comment by Belgabor** [comment]
> How does Tabby deal with it? How are the tabs selected which should receive the input? Is it just all of the tabs/panes in a window?
It's not a feature I have use for, so I'm not really familiar with it's intricacies. As far as I can see from a quick test you can focus either everything (aka all panes on all tabs) or just all the panes on one tab,
